inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 13

Style/BlockLength:
  Exclude:
    - 'spec/**/*spec.rb'
